name: Setup rclone
description: Setup rclone with configuration
inputs:
  rclone_conf:
    description: "rclone config content"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup rclone
      shell: bash
      run: |
        set -euo pipefail
        sudo -v
        curl https://rclone.org/install.sh | sudo bash

    - name: Setup rclone config
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p rclone-config
        cat > rclone-config/rclone.conf <<EOF
        ${{ inputs.rclone_conf }}
        EOF
